## Stetige Regler 
Für das Verständnis von stetigen Reglern ist es hilfreich die Regelungstechnik mathematisch zu betrachten, da sich die ein Regler sehr gut mit Formeln beschreiben und erklären lässt. In einem eigenen Kapitel soll bewhandelt werden wie Regler praxisnahe implementiert werden können.  
Der oben gezeigte Regelkreis, @fig-Regelkreis, lässt sich mathematisch als Übertragungsfunktion beschreiben. Hier werden ausschließlich SISO (Single Input Single Output) Systeme betrachtet. Das Bedeutet Systeme die einen Eingang und einen Ausgang haben. Jeder Block kann einzeln mit einer Übertragungsfunktion, analog der Vierpoltheorie aus KSN, beschrieben werden. Wie auch in der Vierpoltheorie kann aber auch eine Verschaltung von Blöcken als Übertragungsfunktion beschrieben werden. Ein Block wird in der Regelungstechnik auch als **Strecke** bezeichnet.

### Die Übertragungsfunktion
Die Übertragungsfunktion Beschreibt den Zusammenhang zwischen Ausgang und Eingang. Um die Mathematik möglichst einfach zu halten wird in der Regelungstechnik im Laplace Bereich gearbeitet. Dadurch ist  es nicht notwendig die Diffenrentialgleichung bei physikalischen Systemen, die durch eine Differentialgleichung beschrieben werden, zu lösen.   

```{python}
#| code-fold: true
E = MySymbol('E',description = 'Eingang')
V = MySymbol('V',description = 'Verarbeitung, die Übertragungsfunktion')
A = MySymbol('A',description = 'Ausgang')
G = MySymbol('G',description = 'Allgemeine Übertragungsfunktion')

Veq = Eq(V,A/E)

display(Markdown(f'$$\n{latex(Veq)}\n$${{#eq-EVA}}'))

QBookHelpers.print_description(Veq.free_symbols)

```

Gängige Bezeichnungen der Übertragungsfunktion der einzelnen Blöcke ist wie folgt.

```{python}
#| code-fold: true
G = MySymbol('G',description = 'Übertragungsfunktion der zu Regelnden Strecke')
R = MySymbol('R',description = 'Übertragungsfunktion des Reglers')
M = MySymbol('M',description = 'Übertragungsfunktion des Sensors')

QBookHelpers.print_description({G,R,M})

```


{{< include 01.02.01.02_Laplace.qmd >}}


{{< include 01.02.01.03_BlockAlegebra.qmd >}}