## Stetige Regler 
Für das Verständnis von stetigen Reglern ist es hilfreich, die Regelungstechnik mathematisch zu betrachten, da sich ein Regler sehr gut mit Formeln beschreiben und erklären lässt. In einem eigenen Kapitel soll behandelt werden, wie Regler praxisnahe implementiert werden können.  
Der oben gezeigte Regelkreis @fig-Regelkreis lässt sich mathematisch als Übertragungsfunktion beschreiben. Hier werden ausschließlich SISO (Single Input Single Output) und LTI (Linear Time Invariant) Systeme betrachtet. Das bedeutet Systeme, die einen Eingang und einen Ausgang haben. Jeder Block kann einzeln mit einer Übertragungsfunktion oder analog der Vierpoltheorie beschrieben werden. Wie auch in der Vierpoltheorie kann aber auch eine Verschaltung von Blöcken als Übertragungsfunktion beschrieben werden. Ein Block wird in der Regelungstechnik auch als **Strecke** bezeichnet.

### Die Übertragungsfunktion
#### Motivation
Die Übertragungsfunktion beschreibt den Zusammenhang zwischen Ausgang und Eingang.  
Ist die Übertragungsfunktion bekannt, so kann die Strecke und deren Verhalten (der Ausgang) auf verschiedene Eingänge berechnet werden. Dies wird auch Simulation genannt. Für Marketingzwecke könnte die Übertragungsfunktion auch als einfache Form eines "digitalen Zwillings" bezeichnet werden.
Ist die Übertragungsfunktion mathematisch beschrieben, können Regler entworfen und getestet werden, ohne das tatsächliche physikalische Modell benutzen zu müssen. Dies ist speziell sinnvoll, wenn das physikalische System für Testzwecke nicht zur Verfügung steht bzw. nicht für Testzwecke geeignet ist.
Eine Strecke (=physikalisches System) steht z.B. nicht zur Verfügung, wenn: 

* Es sich geographisch woanders befindet  
* Es für die Produktion benötigt wird  
* Es noch nicht gebaut wurde  

Eine Strecke (=physikalisches System) ist nicht geeignet für Testzwecke wenn z.B.:  

* Das System sehr langsam ist (Heizung eines Gebäudes)  
* Ein fehlerhafter Regler großen Schaden anrichten kann  

#### Streckenidentifikation {#sec-Streckenidentifikation}
Als Streckenidentifikation wird der Vorgang beschrieben, von einem physikalischem System das mathematische Modell und die Übertragungsfunktion zu erstellen. Zwei Methoden, wie dieses Ziel erreicht werden kann, werden hier beschrieben.  

* Der mathematische Ansatz, @sec-MathStreckenidentifikation  
* Der messtechnische Ansatz, @sec-MessStreckenidentifikation  


```{python}
#| code-fold: true
E = MySymbol('E',description = 'Eingang')
V = MySymbol('V',description = 'Verarbeitung, die Übertragungsfunktion')
A = MySymbol('A',description = 'Ausgang')
G = MySymbol('G',description = 'Allgemeine Übertragungsfunktion')

Veq = Eq(V,A/E)

display(Markdown(f'$$\n{latex(Veq)}\n$${{#eq-EVA}}'))

QBookHelpers.print_description(Veq.free_symbols)

```

Gängige Bezeichnungen der Übertragungsfunktion der einzelnen Blöcke sind wie folgt.

```{python}
#| code-fold: true
G = MySymbol('G',description = 'Übertragungsfunktion der zu Regelnden Strecke')
R = MySymbol('R',description = 'Übertragungsfunktion des Reglers')
M = MySymbol('M',description = 'Übertragungsfunktion des Sensors')

QBookHelpers.print_description({G,R,M})

```

### Mathematische Streckenidentifikation {#sec-MathStreckenidentifikation}
Aus den physikalischen Zusammenhängen kann die Übertragungsfunktion berechnet werden.
Die komplexe Schreibweise ist nur für periodische sinusförmige Signale geeignet. Sollen Signale betrachtet werden, die beliebig oder stetig sind, ist die komplexe schreibweise nicht ausreichend. Es müssen die physikalischen Gleichungen in differentieller Form angeschrieben werden.

Um die Mathematik möglichst einfach zu halten, wird in der Regelungstechnik im Laplace Bereich gearbeitet. Dadurch ist es nicht notwendig, die Differenzialgleichung bei physikalischen Systemen, die durch eine Differenzialgleichung beschrieben werden, zu lösen.

Ein Beispiel, wie eine mathematische Streckenidentifikation abläuft, ist in Abschnitt @sec-Laplace zu finden.

### Messtechnische Streckenidentifikation {#sec-MessStreckenidentifikation}
Manche Systeme sind zu komplex, um Sie mathematisch zu beschreiben. Andere Systeme sind mathematisch nicht beschreibbar, weil das Innenleben nicht bekannt ist. In diesen Fällen kann die messtechnische Ermittlung der Übertragungsfunktion herangezogen werden.  
Dabei wird am Eingang der Strecke ein Testsignal aufgeschaltet und der Ausgang gemessen. Aus diesen Messdaten kann die Übertragungsfunktion, ein mathematisches Modell, der Strecke erstellt werden.

{{< include 01.02.01.02_Laplace.qmd >}}

{{< include 01.02.02.03_Signale_und_Streckenverhalten.qmd >}}


{{< include 01.02.01.03_BlockAlegebra.qmd >}}


{{< include 01.02.01.04_InteractivePID.qmd >}}