### Zusammenschaltung von Blöcken
Werden Blöcke kombiniert, können die resultierenden Übertragungsfunktionen berechnet werden.  
Zur Vereinfachung kann die Übertragungsfunktion des Sensors mit $M=1$ angenommen werden, $M=1$, wenn dieser im Verhältnis zur Strecke und zum Regler vernachlässigbar ist. Dies ist zum Beispiel der Fall, wenn der Sensor viel schneller ist als die Strecke und der Regler. Diese Voraussetzung ist für viele Systeme gegeben.  

Für den Regelkreis, @fig-Regelkreis, ergeben sich folgende Möglichkeiten.

#### Die Führungsübertragungsfunktion
Die Führungsübertragungsfunktion gibt das Verhältnis zwischen Sollgröße und Istgröße an. Sie beschreibt damit das Verhalten des Regelkreises mit der Sollgröße als Eingang und der Istgröße als Ausgang. Ist eine Regelstrecke ideal, so ist die Führungsübertragungsfunktion gleich Eins.

```{python}
#| code-fold: true
Fw = MySymbol('F_w',description = 'Führungsübertragungsfunktion')

Fw_eq=Eq(Fw,R*G/(1+R*G*M))

display(Markdown(f'$$\n{latex(Fw_eq)}\n$${{#eq-Fw_eq}}'))

QBookHelpers.print_description({Fw})

```

#### Die Schleifenübertragungsfunktion
Die Schleifenübertragungsfunktion ist die Übertragungsfunktion des offenen Regelkreises, also ohne Rückkopplung und ist im Laplace Bereich eine einfache Multiplikation.

```{python}
#| code-fold: true
Fo = MySymbol('F_o',description = 'Schleifenübertragungsfunktion')

Fo_eq=Eq(Fo,R*G)

QBookHelpers.print_equation(Fo_eq)
QBookHelpers.print_description({Fo})

```

#### Die Störübertragungsfunktion
Die Störübertragungsfunktion beschreibt, wie sich die Störgröße auf den Ausgang auswirkt.

```{python}
#| code-fold: true
Fs = MySymbol('F_s',description = 'Störübertragungsfunktion')

Fs_eq=Eq(Fs,G/(1+Fo))

QBookHelpers.print_equation(Fs_eq)
QBookHelpers.print_description({Fs})

```